escproject/escapp/urls.py
from django.urls import path
from .views import *
from . import views 

app_name = "escapp"
urlpatterns = [
    path("", views.index, name = "index"),
    path("index2/", views.index2, name = "index2"),
    # path("", HomeView.as_view(), name='index'),
    path("hotellist/", HotelListView.as_view(), name="hotellist"),
    path("f1/", views.f1, name = "f1"),
    # path("hotellist/", views.hotel_get_context_data, name = "hotellist"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path("booklogin/", BookLoginView.as_view(), name="booklogin"),
    path("booking/", BookingView.as_view(), name="booking"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("hotelinfo/<slug:slug>/", HotelInfoView.as_view(), name = "hotelinfo"),
    path("startbooking/<slug:slug>/", StartBooking.as_view(), name = "startbooking"),
    path("hotelinfo_map/", ViewMap.as_view(), name = "hotelinfo_map"),
    path("hotelrooms/", HotelRoomsView.as_view(), name="hotelrooms"),
    path("accountinfo/", AccountinfoView.as_view(), name="accountinfo"),
    path("deleteaccount/", CheckDeleteAccountView.as_view(), name="deleteaccountcheck"),
    path("confirmdelete/", ConfirmDeleteView.as_view(), name="confirmdelete"),
    path("confirmtransaction/", ConfirmTransactionView.as_view(), name="confirmtransaction"),
    path("bookingdone/", BookingDoneView.as_view(), name="bookingdone"),
    path("deleteuser/", DeleteUserView.as_view(), name="deleteuser"),
    path("f2/", views.f2, name = "f2"),
    path("hotelsearched/", HotelInfoView_V2.as_view(), name="hotelsearched"),
    path("bookinghistory/", views.BookingHistory, name = "bookinghistory"),





]

escproject/escproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("escapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

escproject/templates/confirmtransaction.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <title>Confirm Transaction Page - Ascenda</title>
    <meta property="og:title" content="Confirm Transaction Page - Ascenda" />
    <meta property="og:title" content="Hotel Info Page - Ascenda" />
    <meta property="og:title" content="Booking Confirmation Page - Ascenda" />
    <meta property="og:title" content="About Page - Ascenda" />
    <meta property="og:title" content="Login Page - Ascenda" />
    <meta property="og:title" content="Previous Bookings Page - Ascenda" />
    <meta property="og:title" content="Booking Form Page - Ascenda" />
    <meta
      property="og:title"
      content="Registration Confirmation Page - Ascenda"
    />
    <meta property="og:title" content="Pre-Booking Login Page - Ascenda" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />
    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6 {  margin: 0;  padding: 0;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Roboto;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.55;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./confirm-transaction-page.css" rel="stylesheet" />

      <div class="confirm-transaction-page-container">
        <div class="confirm-transaction-page-container1">
          <div class="confirm-transaction-page-container2">
            <div class="confirm-transaction-page-content-container">
              <span class="confirm-transaction-page-text">
                Would you like to confirm the transaction?
              </span>
              <span class="confirm-transaction-page-text1">
                Payment will be made automatically once you click yes.
              </span>
              <div class="confirm-transaction-page-container3">
                <div class="confirm-transaction-page-container4">
                  <a
                    href="{% url 'escapp:index' %}"
                    class="confirm-transaction-page-navlink1 button"
                  >
                    Cancel
                  </a>
                </div>
                <div class="confirm-transaction-page-container5">
                  <a
                    href="{% url 'escapp:bookingdone' %}"
                    class="confirm-transaction-page-navlink1 button"
                    id="confirm_transaction_button"
                  >
                    Confirm
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://unpkg.com/@teleporthq/teleport-custom-scripts"></script>
    <style>
      .confirm-transaction-page-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: flex-start;
  flex-direction: row;
  justify-content: center;
  background-color: var(--dl-color-primary-darkblue);
}
.confirm-transaction-page-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 1003px;
  display: flex;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-color: var(--dl-color-primary-fadeddblue);
  background-image: url("https://images.unsplash.com/photo-1619634727222-3318c5e9ebd7?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDE0Mnx8aG90ZWx8ZW58MHx8fHwxNjU4NTg1MjIy&ixlib=rb-1.2.1&w=1500");
}
.confirm-transaction-page-container2 {
  flex: 0 0 auto;
  display: flex;
  padding: var(--dl-space-space-doubleunit);
  align-items: flex-start;
  flex-direction: column;
  justify-content: flex-start;
  background-color: var(--dl-color-primary-darkblue);
}
.confirm-transaction-page-content-container {
  width: 1022px;
  height: 427px;
  display: flex;
  padding: var(--dl-space-space-unit);
  position: relative;
  align-self: center;
  margin-top: 0px;
  align-items: center;
  border-color: var(--dl-color-primary-brown);
  border-width: 1px;
  border-radius: var(--dl-radius-radius-radius4);
  flex-direction: column;
  justify-content: center;
}
.confirm-transaction-page-text {
  color: var(--dl-color-primary-brown);
  font-size: 50px;
  align-self: center;
  margin-top: 0px;
  font-family: Roboto;
  padding-left: 0px;
  padding-right: 0px;
}
.confirm-transaction-page-text1 {
  color: var(--dl-color-primary-white);
  font-size: 30px;
  align-self: center;
  margin-top: var(--dl-space-space-unit);
  font-family: Roboto;
  padding-left: var(--dl-space-space-unit);
  margin-bottom: var(--dl-space-space-unit);
  padding-right: var(--dl-space-space-unit);
}
.confirm-transaction-page-container3 {
  width: 688px;
  height: auto;
  display: flex;
  position: relative;
  align-self: center;
  margin-top: var(--dl-space-space-unit);
  align-items: flex-end;
  margin-bottom: var(--dl-space-space-unit);
  flex-direction: row;
  justify-content: space-between;
}
.confirm-transaction-page-container4 {
  display: flex;
  align-items: flex-end;
  border-color: var(--dl-color-primary-brown);
  border-width: 1px;
  flex-direction: row;
  justify-content: space-between;
}
.confirm-transaction-page-navlink {
  color: var(--dl-color-primary-white);
  font-size: 20px;
  align-self: center;
  font-family: Roboto;
  padding-top: var(--dl-space-space-halfunit);
  border-width: 0px;
  margin-right: 0px;
  padding-left: var(--dl-space-space-doubleunit);
  padding-right: var(--dl-space-space-doubleunit);
  padding-bottom: var(--dl-space-space-halfunit);
  text-decoration: none;
  background-color: transparent;
}
.confirm-transaction-page-container5 {
  display: flex;
  align-items: flex-end;
  border-color: var(--dl-color-primary-brown);
  border-width: 1px;
  flex-direction: row;
  justify-content: space-between;
}
.confirm-transaction-page-navlink1 {
  color: var(--dl-color-primary-brown);
  font-size: 20px;
  align-self: center;
  font-family: Roboto;
  margin-left: 0px;
  padding-top: var(--dl-space-space-halfunit);
  border-width: 0px;
  padding-left: var(--dl-space-space-doubleunit);
  padding-right: var(--dl-space-space-doubleunit);
  padding-bottom: var(--dl-space-space-halfunit);
  text-decoration: none;
  background-color: transparent;
}
@media(max-width: 767px) {
  .confirm-transaction-page-content-container {
    align-items: center;
  }
}

    </style>
    <style>
      :root {
  --dl-color-gray-900: #D9D9D9;
  --dl-size-size-unit: 1rem;
  --dl-color-gray-black: #000000;
  --dl-color-gray-white: #FFFFFF;
  --dl-space-space-unit: 1em;
  --dl-color-primary-grey: #edeae5ff;
  --dl-size-size-halfunit: 0.5rem;
  --dl-color-primary-brown: #b69d74ff;
  --dl-color-primary-white: #f5f5efff;
  --dl-radius-radius-round: 50%;
  --dl-size-size-doubleunit: 2rem;
  --dl-size-size-tripleunit: 3rem;
  --dl-space-space-halfunit: 0.5em;
  --dl-radius-radius-radius2: 2px;
  --dl-radius-radius-radius4: 4px;
  --dl-radius-radius-radius8: 8px;
  --dl-space-space-quadruple: 4em;
  --dl-color-primary-darkblue: #1f2839ff;
  --dl-space-space-doubleunit: 2em;
  --dl-space-space-tripleunit: 3em;
  --dl-color-primary-fadeddblue: #1f2839b8;
}
.teleport-show {
  display: flex !important;
}
.button {
  font-size: 14px;
  font-family: Roboto;
  font-weight: 600;
  text-transform: none;
  text-decoration: none;
}
.list-item {
  display: list-item;
}
.list {
  width: 100%;
  margin: 1em 0px 1em 0px;
  display: block;
  padding: 0px 0px 0px 1.5rem;
  list-style-type: none;
  list-style-position: outside;
}
.textarea {
  color: var(--dl-color-gray-black);
  cursor: auto;
  padding: 0.5rem;
  font-family: Roboto;
  border-color: var(--dl-color-gray-black);
  border-width: 1px;
  border-radius: 4px;
  background-color: var(--dl-color-gray-white);
}
.input {
  color: var(--dl-color-gray-black);
  cursor: auto;
  padding: 0.5rem 1rem;
  font-family: Roboto;
  border-color: var(--dl-color-gray-black);
  border-width: 1px;
  border-radius: 4px;
  background-color: var(--dl-color-gray-white);
}
.subheading {
  font-size: 1.6rem;
  font-family: Roboto;
  font-weight: 400;
  text-transform: none;
  text-decoration: none;
}
.heading {
  font-size: 3rem;
  font-family: Roboto;
  font-weight: 700;
  line-height: 1.55;
  text-transform: none;
  text-decoration: none;
}
.content {
  font-size: 16px;
  font-family: Roboto;
  font-weight: 400;
  line-height: 1.55;
  text-transform: none;
  text-decoration: none;
}

    </style>
  </body>
</html>

escproject/templates/hotelInfo_map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Location of Hotel on Map</title>
    {{map.header.render|safe}}
</head>
<body>
  <!-- <a href=""><h1>X</h1></a> -->
  <h6>  <center> Location of hotel</center></h6>

  <style>
    h6{
      font-size: 30px;
      color: white;
    }
    h1{
      font-size: 30px;
      color: white;
      text-align:end;


    }
    body{
      background-color: #1f2839ff;
    }
  </style>

  {{map.html.render|safe}}
  <script>
    {{map.script.render|safe}}
  </script>
  
</body>
</html>

escproject/templates/map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Location of Hotel on Map</title>
    {{map.header.render|safe}}
</head>
<body>
  <div><h6>  Location of hotel as represented by green icon below</h6></div>
  {{map.html.render|safe}}
  <script>
    {{map.script.render|safe}}
  </script>
  
</body>
</html>

escproject/templates/startbooking.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <title>Confirm Transaction Page - Ascenda</title>
    <meta property="og:title" content="Confirm Transaction Page - Ascenda" />
    <meta property="og:title" content="Hotel Info Page - Ascenda" />
    <meta property="og:title" content="Booking Confirmation Page - Ascenda" />
    <meta property="og:title" content="About Page - Ascenda" />
    <meta property="og:title" content="Login Page - Ascenda" />
    <meta property="og:title" content="Previous Bookings Page - Ascenda" />
    <meta property="og:title" content="Booking Form Page - Ascenda" />
    <meta
      property="og:title"
      content="Registration Confirmation Page - Ascenda"
    />
    <meta property="og:title" content="Pre-Booking Login Page - Ascenda" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <meta property="twitter:card" content="summary_large_image" />
    <style data-tag="reset-style-sheet">
      html {  line-height: 1.15;}body {  margin: 0;}* {  box-sizing: border-box;  border-width: 0;  border-style: solid;}p,li,ul,pre,div,h1,h2,h3,h4,h5,h6 {  margin: 0;  padding: 0;}button,input,optgroup,select,textarea {  font-family: inherit;  font-size: 100%;  line-height: 1.15;  margin: 0;}button,select {  text-transform: none;}button,[type="button"],[type="reset"],[type="submit"] {  -webkit-appearance: button;}button::-moz-focus-inner,[type="button"]::-moz-focus-inner,[type="reset"]::-moz-focus-inner,[type="submit"]::-moz-focus-inner {  border-style: none;  padding: 0;}button:-moz-focus,[type="button"]:-moz-focus,[type="reset"]:-moz-focus,[type="submit"]:-moz-focus {  outline: 1px dotted ButtonText;}a {  color: inherit;  text-decoration: inherit;}input {  padding: 2px 4px;}img {  display: block;}html { scroll-behavior: smooth  }
    </style>
    <style data-tag="default-style-sheet">
      html {
        font-family: Roboto;
        font-size: 16px;
      }

      body {
        font-weight: 400;
        font-style:normal;
        text-decoration: none;
        text-transform: none;
        letter-spacing: normal;
        line-height: 1.55;
        color: var(--dl-color-gray-black);
        background-color: var(--dl-color-gray-white);

      }
    </style>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      data-tag="font"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      data-tag="font"
    />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <div>
      <link href="./confirm-transaction-page.css" rel="stylesheet" />

      <div class="confirm-transaction-page-container">
        <div class="confirm-transaction-page-container1">
          <div class="confirm-transaction-page-container2">
            <div class="confirm-transaction-page-content-container">
              <span class="confirm-transaction-page-text">
                Would you like to proceed to payment?
              </span>
              {% if request.user.customer %}
              <span class="confirm-transaction-page-text1">
                Please ready your credit card information.
              </span>
              {% else %}
              <span class="confirm-transaction-page-text1">
                You are required to login before you can proceed.
              </span>
              {% endif %}
              <div class="confirm-transaction-page-container3">
                <div class="confirm-transaction-page-container4">
                  <a
                    href="{% url 'escapp:hotelrooms' %}"
                    class="confirm-transaction-page-navlink1 button"
                  >
                    Back
                  </a>
                </div>
                
              {% if request.user.customer %}
                <div class="confirm-transaction-page-container5">
                  <a
                    href="{% url 'escapp:booking' %}"
                    class="confirm-transaction-page-navlink1 button"
                    id="payment_button"
                  >
                    Proceed to Payment
                  </a>
                </div>
                {% else %}
                <div class="confirm-transaction-page-container5">
                  <a
                    href="{% url 'escapp:booklogin' %}"
                    class="confirm-transaction-page-navlink1 button"
                    id="booking_login_button"
                  >
                    Log In
                  </a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://unpkg.com/@teleporthq/teleport-custom-scripts"></script>
    <style>
      .confirm-transaction-page-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: flex-start;
  flex-direction: row;
  justify-content: center;
  background-color: var(--dl-color-primary-darkblue);
}
.confirm-transaction-page-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 1003px;
  display: flex;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-color: var(--dl-color-primary-fadeddblue);
  background-image: url("https://images.unsplash.com/photo-1619634727222-3318c5e9ebd7?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDE0Mnx8aG90ZWx8ZW58MHx8fHwxNjU4NTg1MjIy&ixlib=rb-1.2.1&w=1500");
}
.confirm-transaction-page-container2 {
  flex: 0 0 auto;
  display: flex;
  padding: var(--dl-space-space-doubleunit);
  align-items: flex-start;
  flex-direction: column;
  justify-content: flex-start;
  background-color: var(--dl-color-primary-darkblue);
}
.confirm-transaction-page-content-container {
  width: 1022px;
  height: 427px;
  display: flex;
  padding: var(--dl-space-space-unit);
  position: relative;
  align-self: center;
  margin-top: 0px;
  align-items: center;
  border-color: var(--dl-color-primary-brown);
  border-width: 1px;
  border-radius: var(--dl-radius-radius-radius4);
  flex-direction: column;
  justify-content: center;
}
.confirm-transaction-page-text {
  color: var(--dl-color-primary-brown);
  font-size: 50px;
  align-self: center;
  margin-top: 0px;
  font-family: Roboto;
  padding-left: 0px;
  padding-right: 0px;
}
.confirm-transaction-page-text1 {
  color: var(--dl-color-primary-white);
  font-size: 30px;
  align-self: center;
  margin-top: var(--dl-space-space-unit);
  font-family: Roboto;
  padding-left: var(--dl-space-space-unit);
  margin-bottom: var(--dl-space-space-unit);
  padding-right: var(--dl-space-space-unit);
}
.confirm-transaction-page-container3 {
  width: 688px;
  height: auto;
  display: flex;
  position: relative;
  align-self: center;
  margin-top: var(--dl-space-space-unit);
  align-items: flex-end;
  margin-bottom: var(--dl-space-space-unit);
  flex-direction: row;
  justify-content: space-between;
}
.confirm-transaction-page-container4 {
  display: flex;
  align-items: flex-end;
  border-color: var(--dl-color-primary-brown);
  border-width: 1px;
  flex-direction: row;
  justify-content: space-between;
}
.confirm-transaction-page-navlink {
  color: var(--dl-color-primary-white);
  font-size: 20px;
  align-self: center;
  font-family: Roboto;
  padding-top: var(--dl-space-space-halfunit);
  border-width: 0px;
  margin-right: 0px;
  padding-left: var(--dl-space-space-doubleunit);
  padding-right: var(--dl-space-space-doubleunit);
  padding-bottom: var(--dl-space-space-halfunit);
  text-decoration: none;
  background-color: transparent;
}
.confirm-transaction-page-container5 {
  display: flex;
  align-items: flex-end;
  border-color: var(--dl-color-primary-brown);
  border-width: 1px;
  flex-direction: row;
  justify-content: space-between;
}
.confirm-transaction-page-navlink1 {
  color: var(--dl-color-primary-brown);
  font-size: 20px;
  align-self: center;
  font-family: Roboto;
  margin-left: 0px;
  padding-top: var(--dl-space-space-halfunit);
  border-width: 0px;
  padding-left: var(--dl-space-space-doubleunit);
  padding-right: var(--dl-space-space-doubleunit);
  padding-bottom: var(--dl-space-space-halfunit);
  text-decoration: none;
  background-color: transparent;
}
@media(max-width: 767px) {
  .confirm-transaction-page-content-container {
    align-items: center;
  }
}

    </style>
    <style>
      :root {
  --dl-color-gray-900: #D9D9D9;
  --dl-size-size-unit: 1rem;
  --dl-color-gray-black: #000000;
  --dl-color-gray-white: #FFFFFF;
  --dl-space-space-unit: 1em;
  --dl-color-primary-grey: #edeae5ff;
  --dl-size-size-halfunit: 0.5rem;
  --dl-color-primary-brown: #b69d74ff;
  --dl-color-primary-white: #f5f5efff;
  --dl-radius-radius-round: 50%;
  --dl-size-size-doubleunit: 2rem;
  --dl-size-size-tripleunit: 3rem;
  --dl-space-space-halfunit: 0.5em;
  --dl-radius-radius-radius2: 2px;
  --dl-radius-radius-radius4: 4px;
  --dl-radius-radius-radius8: 8px;
  --dl-space-space-quadruple: 4em;
  --dl-color-primary-darkblue: #1f2839ff;
  --dl-space-space-doubleunit: 2em;
  --dl-space-space-tripleunit: 3em;
  --dl-color-primary-fadeddblue: #1f2839b8;
}
.teleport-show {
  display: flex !important;
}
.button {
  font-size: 14px;
  font-family: Roboto;
  font-weight: 600;
  text-transform: none;
  text-decoration: none;
}
.list-item {
  display: list-item;
}
.list {
  width: 100%;
  margin: 1em 0px 1em 0px;
  display: block;
  padding: 0px 0px 0px 1.5rem;
  list-style-type: none;
  list-style-position: outside;
}
.textarea {
  color: var(--dl-color-gray-black);
  cursor: auto;
  padding: 0.5rem;
  font-family: Roboto;
  border-color: var(--dl-color-gray-black);
  border-width: 1px;
  border-radius: 4px;
  background-color: var(--dl-color-gray-white);
}
.input {
  color: var(--dl-color-gray-black);
  cursor: auto;
  padding: 0.5rem 1rem;
  font-family: Roboto;
  border-color: var(--dl-color-gray-black);
  border-width: 1px;
  border-radius: 4px;
  background-color: var(--dl-color-gray-white);
}
.subheading {
  font-size: 1.6rem;
  font-family: Roboto;
  font-weight: 400;
  text-transform: none;
  text-decoration: none;
}
.heading {
  font-size: 3rem;
  font-family: Roboto;
  font-weight: 700;
  line-height: 1.55;
  text-transform: none;
  text-decoration: none;
}
.content {
  font-size: 16px;
  font-family: Roboto;
  font-weight: 400;
  line-height: 1.55;
  text-transform: none;
  text-decoration: none;
}

    </style>
  </body>
</html>
